services:
  - type: web
    name: Empire_X
    buildCommand: "npm install"  # Install dependencies
    startCommand: "pm2 start index.js --deep-monitoring --attach --name Empire_X"  # Start command with PM2
    plan: free  # Choose the free plan, or upgrade depending on your needs
    runtime: "node"  # Use the Node.js runtime (this should work on Render)
    envVars:
      - key: OWNER_NUMBER
        value: "2348078582627"  # Replace with your actual owner's phone number
      - key: OWNER_NAME
        value: "Ony_one_ðŸ¥‡Empire"  # Replace with owner name 
      - key: BOT_NAME
        value: "Empire_X"  # Do not change
      - key: SESSION_ID
        value: "fIEDHbyS#bOM1Jr3x-TGE4AHjpozvUqZhJAu__we9izki9NP5aU0"  # Replace with your actual session ID (if needed)
      - key: PREFIX
        value: "."  # Your bot's prefix
      - key: MODE
        value: "private"  # Set the bot's mode: "private" or "groups"
      - key: AUTO_READ_STATUS
        value: "false"  # Enable auto-read status
      - key: AUTO_REACT
        value: "false"  # Enable auto reactions if required
      - key: OWNER_REACT
        value: "true"  # Enable owner-specific reactions if needed
      - key: ALIVE_IMG
        value: "https://raw.githubusercontent.com/efeurhobo/Empire_X/main/lib/assets/empire.jpg"  # Replace with owner
      - key: AIVE_MSG
        value: "HI DEAR EMPIRE_X IS ACTIVE"  # Replace with owner